app/models.py
from datetime import datetime

from app import db


class Summary(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    summary = db.Column(db.String())
    url = db.Column(db.String())
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __init__(self, title, summary, url):
        self.title = title
        self.summary = summary
        self.url = url

    def __repr__(self):
        return f'<Summary {self.title}>'

app/__init__.py
import logging
import os
from logging.handlers import RotatingFileHandler

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        # ...

        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/summarizerbot.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('SummarizerBot')

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, current_app

from app import db
from app.models import Summary
from app.main import bp


@bp.route('/')
def index():
    # summaries = Summary.query.order_by().limit(30)
    # summaries = Summary.query.limit(15).all()
    summaries = Summary.query.all()[-15:-1]
    title = "This is the future"
    return render_template('index.html', title=title, summaries=summaries)


@bp.route('/blog/<int:summary_id>')
def detail(summary_id):
    summary = Summary.query.get(summary_id)
    return render_template('detail.html', summary=summary)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title> SummarizerBot - Read the news in 3 paragraphs.</title>
    <style>
        .landpage {

           background-color: #ffffff;
           background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='152' height='152' viewBox='0 0 152 152'%3E%3Cg fill-rule='evenodd'%3E%3Cg id='temple' fill='%23c6e2cb' fill-opacity='0.4'%3E%3Cpath d='M152 150v2H0v-2h28v-8H8v-20H0v-2h8V80h42v20h20v42H30v8h90v-8H80v-42h20V80h42v40h8V30h-8v40h-42V50H80V8h40V0h2v8h20v20h8V0h2v150zm-2 0v-28h-8v20h-20v8h28zM82 30v18h18V30H82zm20 18h20v20h18V30h-20V10H82v18h20v20zm0 2v18h18V50h-18zm20-22h18V10h-18v18zm-54 92v-18H50v18h18zm-20-18H28V82H10v38h20v20h38v-18H48v-20zm0-2V82H30v18h18zm-20 22H10v18h18v-18zm54 0v18h38v-20h20V82h-18v20h-20v20H82zm18-20H82v18h18v-18zm2-2h18V82h-18v18zm20 40v-18h18v18h-18zM30 0h-2v8H8v20H0v2h8v40h42V50h20V8H30V0zm20 48h18V30H50v18zm18-20H48v20H28v20H10V30h20V10h38v18zM30 50h18v18H30V50zm-2-40H10v18h18V10z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
        }
    </style>
</head>
<body>
    <header class="sticky top-0">
        <div class="flex flex-row justify-between m-8 bg-white">
            <h1 class="font-mono text-1xl bg-white p-4 text-black subpixel-antialiased">SummarizerBot</h1>
            <p class="p-4 text-white text-1xl rounded-3xl font-medium bg-green-700"><a target="_blank" href="https://twitter.com/summarizerbot">Follow</a></p>
        </div>
    </header>

    {% block content %}

    {% endblock %}
</body>
</html>

app/templates/detail.html
{% extends "landpage.html" %}

{% block content %}
    <div class="mx-64 mt-8 p-16 rounded-b-lg border-green-700 border-t-2 shadow-lg">
        <h1 class="text-6xl text-center">{{ summary.title }}</h1>
        <p class="text-center text-sm p-8 text-green-700"><a target="_blank" href="{{ summary.url }}">FULL ARTICLE</a></p>

        <p class="text-justify text-base">{{ summary.summary }}</p>
    </div>


{% endblock %}

app/templates/index.html
    {% include 'landpage.html' %}

    {% block content %}
        <div class="mx-40 mb-40 mt-24 bg-white">

            <h2 class="py-8 text-2xl">Latest</h2>

            <div class="grid grid-cols-3 gap-4">

                {% for summary in summaries %}
                    <div class="rounded-b-lg border-t-2 border-green-700 shadow-lg px-4 pt-4 pb-2 border-gray-200 space-y-16">
                        <h2 class="text-2xl text-center">{{ summary.title }}</h2>
                        <p class="text-green-700 hover:underline text-center"><a href="{{ url_for('main.detail', summary_id=summary.id ) }}">Read more...</a></p>
                    </div>
                {% endfor %}
            </div>

        </div>

    {% endblock %}

app/templates/landpage.html
{% extends "base.html" %}

    {% block content %}
        <div class="container bg-white px-24 pb-24 pt-8 space-y-24 landpage">
            <p class="text-center text-4xl font-extrabold text-green-700 text-opacity-75 subpixel-antialiased">Summarize any type of information on Twitter</p>

            <div class="flex flex-row space-x-32">
                <div class="space-y-10">
                    <h4 class="text-3xl font-medium">How it works</h4>

                    <div class="space-y-10">
                        <div class="flex flex-row space-x-3">
                            <svg class="text-green-700 h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v3.586L7.707 9.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 10.586V7z" clip-rule="evenodd" />
                            </svg>
                            <p>Mention the bot as a reply</p>
                        </div>
                        <div class="flex flex-row space-x-3">
                            <svg class="text-green-700 h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v3.586L7.707 9.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 10.586V7z" clip-rule="evenodd" />
                            </svg>
                            <p>Follow the bot to get updates</p>
                        </div>
                        <div class="flex flex-row space-x-3">
                            <svg class="text-green-700 h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v3.586L7.707 9.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 10.586V7z" clip-rule="evenodd" />
                            </svg>
                            <p>Click on the link</p>
                        </div>
                    </div>

                </div>

                <div class="p-2 shadow-2xl bg-green-700 rounded-3xl">
                    <img src="https://res.cloudinary.com/iyanuashiri/image/upload/v1609185899/summarizer2.png">
                </div>

            </div>

        </div>

    {% endblock %}